version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.16
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
    #  - run:
    #      name: Run tests
    #      command: pytest

  deploy:
    machine:
        enabled: true
    steps:
        - run:
            name: Deploy Over SSH
            command: |
              ssh root@143.198.178.203 "/root/update-avbot3.sh"

workflows:
  main:
    jobs:
        - build-and-test
        - deploy:
            requires:
                - build-and-test